# Generated by Django 3.2.8 on 2022-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_exercise_musclegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
    ]
