# Generated by Django 3.2.8 on 2022-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
